version: 2.1
jobs:
  build:
    working_directory: ~/main
    docker:
      - image: circleci/node:10.16.3
    steps:
      - install:
          name: Install Dependencies
          command: npm install
      - build:
          command: npm run build
      - RUN: 
          COMMAND: npm run start